using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TShockAPI;

namespace JgransEconomySystem
{
	public static class NPCType
	{
		// NPC netIDs for hostile NPCs
		private static readonly HashSet<int> HostileNPCs = new HashSet<int>
		{
			NPCID.BlueSlime,
			NPCID.Zombie,
			NPCID.DemonEye,
			NPCID.Crimera,
			NPCID.EaterofSouls,
			NPCID.CaveBat,
			NPCID.JungleBat,
			NPCID.IceBat,
			NPCID.SkeletronHead,
			NPCID.WallCreeper,
			NPCID.WallCreeperWall,
			NPCID.LavaSlime,
			NPCID.Hellbat,
			NPCID.Vulture,
			NPCID.GiantWormHead,
			NPCID.GiantWormBody,
			NPCID.GiantWormTail,
			NPCID.EaterofWorldsHead,
			NPCID.EaterofWorldsBody,
			NPCID.EaterofWorldsTail,
			NPCID.LeechHead,
			NPCID.LeechBody,
			NPCID.LeechTail,
			NPCID.SeekerHead,
			NPCID.SeekerBody,
			NPCID.SeekerTail,
			NPCID.Clown,
			NPCID.CorruptBunny,
			NPCID.CorruptGoldfish,
			NPCID.CorruptPenguin,
			NPCID.CorruptSlime,
			NPCID.CursedHammer,
			NPCID.Crimslime,
			NPCID.CursedSkull,
			NPCID.DarkCaster,
			NPCID.Demon,
			NPCID.WanderingEye,
			NPCID.CataractEye,
			NPCID.SleepyEye,
			NPCID.DialatedEye,
			NPCID.GreenEye,
			NPCID.PurpleEye,
			NPCID.FireImp,
			NPCID.GoblinPeon,
			NPCID.GoblinThief,
			NPCID.GoblinWarrior,
			NPCID.GoblinSorcerer,
			NPCID.ChatteringTeethBomb,
			NPCID.Piranha,
			NPCID.AngryNimbus,
			NPCID.AnomuraFungus,
			NPCID.Antlion,
			NPCID.ArmoredSkeleton,
			NPCID.BigMimicCorruption,
			NPCID.BigMimicCrimson,
			NPCID.BigMimicHallow,
			NPCID.BoneSerpentHead,
			NPCID.BoneSerpentBody,
			NPCID.BoneSerpentTail,
			NPCID.Bunny,
			NPCID.Clinger,
			NPCID.CochinealBeetle,
			NPCID.Corruptor,
			NPCID.Crawdad,
			NPCID.Crimera,
			NPCID.CrimsonAxe,
			NPCID.CursedSkull,
			NPCID.DeadlySphere,
			NPCID.DevourerHead,
			NPCID.DevourerBody,
			NPCID.DevourerTail,
			NPCID.DiggerHead,
			NPCID.DiggerBody,
			NPCID.DiggerTail,
			NPCID.DrManFly,
			NPCID.DungeonSlime,
			NPCID.EaterofSouls,
			NPCID.EnchantedSword,
			NPCID.FlyingAntlion,
			NPCID.FlyingFish,
			NPCID.FlyingSnake,
			NPCID.Frankenstein,
			NPCID.FungiBulb,
			NPCID.Gastropod,
			NPCID.GiantBat,
			NPCID.GiantFlyingFox,
			NPCID.GoblinArcher,
			NPCID.GoblinSummoner,
			NPCID.GoblinWarrior,
			NPCID.Goldfish,
			NPCID.Harpy,
			NPCID.Hellbat,
			NPCID.Herpling,
			NPCID.Hornet,
			NPCID.IceBat,
			NPCID.IceGolem,
			NPCID.IceSlime,
			NPCID.IchorSticker,
			NPCID.IlluminantBat,
			NPCID.JungleBat,
			NPCID.JungleCreeper,
			NPCID.JungleSlime,
			NPCID.LavaSlime,
			NPCID.LeechHead,
			NPCID.LeechBody,
			NPCID.LeechTail,
			NPCID.MartianDrone,
			NPCID.MartianEngineer,
			NPCID.MartianOfficer,
			NPCID.MartianSaucer,
			NPCID.MartianTurret,
			NPCID.Mimic,
			NPCID.MotherSlime,
			NPCID.MushiLadybug,
			NPCID.Paladin,
			NPCID.Parrot,
			NPCID.Penguin,
			NPCID.PirateCorsair,
			NPCID.PirateCrossbower,
			NPCID.PirateDeadeye,
			NPCID.PirateShip,
			NPCID.PirateShipCannon,
			NPCID.Pixie,
			NPCID.Plantera,
			NPCID.PossessedArmor,
			NPCID.RainbowSlime,
			NPCID.RedDevil,
			NPCID.RuneWizard,
			NPCID.RustyArmoredBonesAxe,
			NPCID.RustyArmoredBonesFlail,
			NPCID.RustyArmoredBonesSword,
			NPCID.SandElemental,
			NPCID.SandShark,
			NPCID.SeekerBody,
			NPCID.SeekerHead,
			NPCID.SeekerTail,
			NPCID.ServantofCthulhu,
			NPCID.Shark,
			NPCID.Skeleton,
			NPCID.SkeletonArcher,
			NPCID.SkeletonCommando,
			NPCID.SkeletonSniper,
			NPCID.SlimeMasked,
			NPCID.SlimedZombie,
			NPCID.Snatcher,
			NPCID.SnowBalla,
			NPCID.SnowFlinx,
			NPCID.SnowmanGangsta,
			NPCID.SpikedIceSlime,
			NPCID.SpikedJungleSlime,
			NPCID.SpikedIceSlime,
			NPCID.SpikedJungleSlime,
			NPCID.Squid,
			NPCID.StardustCellBig,
			NPCID.StardustCellSmall,
			NPCID.StardustJellyfishBig,
			NPCID.StardustJellyfishSmall,
			NPCID.StardustSoldier,
			NPCID.StardustSpiderBig,
			NPCID.StardustSpiderSmall,
			NPCID.StardustWormBody,
			NPCID.StardustWormHead,
			NPCID.StardustWormTail,
			NPCID.TacticalSkeleton,
			NPCID.TheGroom,
			NPCID.Tim,
			NPCID.TombCrawlerBody,
			NPCID.TombCrawlerHead,
			NPCID.TombCrawlerTail,
			NPCID.ToxicSludge,
			NPCID.Tumbleweed,
			NPCID.UndeadMiner,
			NPCID.UndeadViking,
			NPCID.Unicorn,
			NPCID.VampireBat,
			NPCID.Vulture,
			NPCID.WallCreeper,
			NPCID.WallCreeperWall,
			NPCID.Wraith,
			NPCID.Zombie,
			NPCID.ZombieEskimo,
			NPCID.ZombieMerman,
			NPCID.ZombieRaincoat,
			NPCID.ZombieSuperman,
			NPCID.ZombiePixie,
			NPCID.ZombieXmas,
			NPCID.ZombieDoctor,
			NPCID.ZombieSweater,
			NPCID.ZombieElf,
			NPCID.ZombieMushroom,
			NPCID.ZombieSuperman,
			NPCID.ZombieDoctor,
			NPCID.ZombieMushroom,
			NPCID.ZombieSuperman,
			NPCID.ZombieRaincoat,
			NPCID.ZombiePixie,
			NPCID.ZombieXmas,
			NPCID.ZombieDoctor,
			NPCID.ZombieSweater,
			NPCID.ZombieElf,
			NPCID.ZombieMushroom,
			NPCID.ZombieSuperman,
			NPCID.MeteorHead,
			NPCID.WanderingEye,
			NPCID.CataractEye,
			NPCID.SleepyEye,
			NPCID.DialatedEye,
			NPCID.GreenEye,
			NPCID.PurpleEye
			// Add more hostile NPCs as needed
		};

		private static readonly HashSet<int> SpecialNPCs = new HashSet<int>
		{

		};

		// NPC IDs for boss NPCs
		private static readonly HashSet<int> BossNPCs = new HashSet<int>
		{
			NPCID.KingSlime,
			NPCID.EyeofCthulhu,
			NPCID.EaterofWorldsHead,
			NPCID.BrainofCthulhu,
			NPCID.QueenBee,
			NPCID.SkeletronHead,
			NPCID.WallofFlesh,
			NPCID.TheDestroyer,
			NPCID.SkeletronPrime,
			NPCID.Retinazer,
			NPCID.Medusa,
			NPCID.Spazmatism,
			NPCID.Plantera,
			NPCID.EmpressButterfly,
			NPCID.Golem,
			NPCID.DukeFishron,
			NPCID.CultistBoss,
			NPCID.MoonLordCore
			// Add more boss NPCs as needed
		};

		public static bool IsHostile(int npcId)
		{
			return HostileNPCs.Contains(npcId);
		}

		public static bool IsSpecial(int npcId)
		{
			return SpecialNPCs.Contains(npcId);
		}

		public static bool IsBoss(int npcId)
		{
			return BossNPCs.Contains(npcId);
		}
	}
}
